theme: jekyll-theme-primer
source: .
destination: _site

# Exclude files and folders from Jekyll build
exclude:
  - ".git"
  - ".gitignore"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor"
